language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t pels/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pels/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-894263465073"
    bucket_path: "docker-react"
    on:
        branch: master

